substitutions:
  _PUBLIC_APPWRITE_PROJECT_ID: ''
  _PUBLIC_APPWRITE_PROJECT_NAME: ''
  _PUBLIC_APPWRITE_ENDPOINT: ''
  _R2_ENDPOINT: ''
  _R2_ACCESS_KEY_ID: ''
  _R2_BUCKET_NAME: ''
  _UPSTASH_REDIS_REST_URL: ''
  _ORIGIN: ''
  _PROTOCOL_HEADER: 'x-forwarded-proto'
  _HOST_HEADER: 'x-forwarded-host'

steps:
  # KROK 1: Pull cache
  - name: 'gcr.io/cloud-builders/docker'
    id: Pull-Latest-For-Cache
    entrypoint: 'bash'
    args:
      - '-c'
      - 'docker pull europe-central2-docker.pkg.dev/$PROJECT_ID/effinity-cloud/app:latest || exit 0'

  # KROK 2: Build
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          -t europe-central2-docker.pkg.dev/$PROJECT_ID/effinity-cloud/app:$SHORT_SHA \
          --cache-from europe-central2-docker.pkg.dev/$PROJECT_ID/effinity-cloud/app:latest \
          --build-arg PUBLIC_APPWRITE_PROJECT_ID=${_PUBLIC_APPWRITE_PROJECT_ID} \
          --build-arg PUBLIC_APPWRITE_PROJECT_NAME=${_PUBLIC_APPWRITE_PROJECT_NAME} \
          --build-arg PUBLIC_APPWRITE_ENDPOINT=${_PUBLIC_APPWRITE_ENDPOINT} \
          --build-arg APPWRITE_API_KEY=$$APPWRITE_API_KEY \
          --build-arg R2_ENDPOINT=${_R2_ENDPOINT} \
          --build-arg R2_ACCESS_KEY_ID=${_R2_ACCESS_KEY_ID} \
          --build-arg R2_SECRET_ACCESS_KEY=$$R2_SECRET_ACCESS_KEY \
          --build-arg R2_BUCKET_NAME=${_R2_BUCKET_NAME} \
          --build-arg UPSTASH_REDIS_REST_URL=${_UPSTASH_REDIS_REST_URL} \
          --build-arg UPSTASH_REDIS_REST_TOKEN=$$UPSTASH_REDIS_REST_TOKEN \
          --build-arg ORIGIN=${_ORIGIN} \
          .
    secretEnv: ['APPWRITE_API_KEY', 'R2_SECRET_ACCESS_KEY', 'UPSTASH_REDIS_REST_TOKEN']

  # KROK 3: Tag Latest
  - name: 'gcr.io/cloud-builders/docker'
    id: Tag-As-Latest
    args:
      - 'tag'
      - 'europe-central2-docker.pkg.dev/$PROJECT_ID/effinity-cloud/app:$SHORT_SHA'
      - 'europe-central2-docker.pkg.dev/$PROJECT_ID/effinity-cloud/app:latest'

  # KROK 4: Push SHA
  - name: 'gcr.io/cloud-builders/docker'
    id: Push-SHA-Tag
    args: ['push', 'europe-central2-docker.pkg.dev/$PROJECT_ID/effinity-cloud/app:$SHORT_SHA']

  # KROK 5: Push Latest
  - name: 'gcr.io/cloud-builders/docker'
    id: Push-Latest-Tag
    args: ['push', 'europe-central2-docker.pkg.dev/$PROJECT_ID/effinity-cloud/app:latest']

# KROK 6: Deploy Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Deploy-To-Cloud-Run
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'effinity-cloud'
      - '--image'
      - 'europe-central2-docker.pkg.dev/$PROJECT_ID/effinity-cloud/app:$SHORT_SHA'
      - '--region'
      - 'europe-central2'
      - '--platform'
      - 'managed'
      - '--port'
      - '3000'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NODE_ENV=production,ORIGIN=${_ORIGIN},PROTOCOL_HEADER=${_PROTOCOL_HEADER},HOST_HEADER=${_HOST_HEADER},PUBLIC_APPWRITE_PROJECT_ID=${_PUBLIC_APPWRITE_PROJECT_ID},PUBLIC_APPWRITE_PROJECT_NAME=${_PUBLIC_APPWRITE_PROJECT_NAME},PUBLIC_APPWRITE_ENDPOINT=${_PUBLIC_APPWRITE_ENDPOINT},R2_ENDPOINT=${_R2_ENDPOINT},R2_ACCESS_KEY_ID=${_R2_ACCESS_KEY_ID},R2_BUCKET_NAME=${_R2_BUCKET_NAME},UPSTASH_REDIS_REST_URL=${_UPSTASH_REDIS_REST_URL}'
      - '--set-secrets'
      - 'APPWRITE_API_KEY=APPWRITE_API_KEY:latest,R2_SECRET_ACCESS_KEY=R2_SECRET_ACCESS_KEY:latest,UPSTASH_REDIS_REST_TOKEN=UPSTASH_REDIS_REST_TOKEN:latest'
    waitFor:
      - 'Push-SHA-Tag'

options:
  logging: CLOUD_LOGGING_ONLY

images:
  - 'europe-central2-docker.pkg.dev/$PROJECT_ID/effinity-cloud/app:$SHORT_SHA'
  - 'europe-central2-docker.pkg.dev/$PROJECT_ID/effinity-cloud/app:latest'

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/APPWRITE_API_KEY/versions/latest
      env: 'APPWRITE_API_KEY'
    - versionName: projects/$PROJECT_ID/secrets/R2_SECRET_ACCESS_KEY/versions/latest
      env: 'R2_SECRET_ACCESS_KEY'
    - versionName: projects/$PROJECT_ID/secrets/UPSTASH_REDIS_REST_TOKEN/versions/latest
      env: 'UPSTASH_REDIS_REST_TOKEN'
